apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: 319538390009.dkr.ecr.eu-west-1.amazonaws.com/alexgtestecr:v0.2
  imagePullSecrets:
    - name: alexgtestecr
