apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  destination:
    namespace: argocd-app
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: app1
    repoURL: "https://github.com/alexgrud/argocd-examples"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
