apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: argocd
spec:
  destination:
    namespace: alexg-helm
    server: "https://kubernetes.default.svc"
  project: test-project
  sources:
    - path: helm-app
      repoURL: "https://github.com/alexgrud/argocd-examples"
      targetRevision: main
      helm:
        releaseName: helloworld
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
